package Concordance::Bs2birdseed;

=head1 NAME

Concordance::Bs2birdseed;

=head1 SYNOPSIS

=head1 DESCRIPTION

=head2 Methods

=cut

use strict;
use warnings;

use Carp;
use Config::General;
use File::Copy;
use Log::Log4perl;
use Concordance::Utils;

if (!Log::Log4perl->initialized()) {
	Log::Log4perl->init("/users/p-qc/dev_concordance_pipeline/Concordance/log4perl.cfg");            
}
my $error_log = Log::Log4perl->get_logger("errorLogger");
my $debug_log = Log::Log4perl->get_logger("debugLogger");

sub new {
	my $self = {};
	$self->{path} = undef;
	bless($self);
	return $self;
}

sub path {
	my $self = shift;
	if (@_) { $self->{path} = shift; }
	return $self->{path}; #[^\0]+
}

sub execute {
	my $self = shift;
	my @files = Concordance::Utils->get_file_list($self->path, "bs");
	my $size = @files;

	foreach my $file (@files) {
		$file =~ /.*\/([^\.]+).*$/;
		my $outfile=$1.".birdseed";
		$debug_log->debug("Converting $file to $outfile\n");
		open(FOUT,"> $outfile");
		open(FIN,"$file");
		while (<FIN>) {
			chomp;
			if (/^\[/ || /^\@/) {
				# do nothing
			} else {
				my @a=split(/\s+/);
				print FOUT "$a[0]\t$a[1]\t$a[2]\t$a[5]\n";
			}
		}
		close(FIN);
		close(FOUT);
	}
}

1;

=head1 NAME

Concordance::Bs2birdseed - converts .bs to .birdseed

=head1 SYNOPSIS

 use Concordance::Bs2birdseed;
 my $bs_2_birdseed = Concordance::Bs2birdseed->new;
 $bs_2_birdseed->convert_bs_to_birdseed;
 $bs_2_birdseed->move_birdseed_to_project_dir;

=head1 DESCRIPTION

This script converts the .bs files generated by buildGELI.pl into .birdseed files, writing out only the desired columns from the input.  It then moves the .birdseed files to the project directory.

=head2 Methods

=over 12

=item C<new>

Returns a new Concordance::Bs2birdseed object.

=item C<convert_bs_to_birdseed>

Converts each .bs file in a specified directory to a .birdseed.

=item C<move_birdseed_to_project_dir>

Tests for the existence of the project directory and creates it if necessary, then moves the .birdseed files there.

=back

=head1 LICENSE

This script is the property of Baylor College of Medicine.

=head1 AUTHOR

Updated by John McAdams - L<mailto:mcadams@bcm.edu>

=cut
